language: objective-c
matrix:
    include:
        - osx_image: xcode8.2

before_install:
    - brew update
    - brew unlink carthage
    - brew install carthage
    - carthage bootstrap --no-use-binaries --platform ios

script:
    - xcodebuild -scheme cqnt -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.2,name=iPhone 7' -configuration Debug test | xcpretty -c
