language: objective-c
matrix:
    include:
        - osx_image: xcode8.2

before_install:
    - brew update
    - brew unlink carthage
    - brew install carthage
    - carthage bootstrap --no-use-binaries --platform ios

script:
  - xcodebuild -scheme cqnt -sdk iphonesimulator -destination 'platform=iOS Simulator,id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12,OS=10.2' -configuration Debug test | xcpretty -c
